function striosomalityLicks(twdb)


% Author: QZ
% 07/30/2019
% bayesianAnalysis.m

%% Part IV. Plot Traces for each mouse at each of the 4 levels
% WT Strio Learn
mouseIDs_WTStrioLearn = unique(twdb_lookup(twdb,'mouseID','key','Health','WT',...
    'key','intendedStriosomality','Strio','grade','learnedFirstTask',0,inf));
% mouseInfo_WTStrioLearn = 'WT Strio Learned';
[rTrace0_WTStrioLearn,rTrace1_WTStrioLearn,rTrace2_WTStrioLearn,...
    rTrace3_WTStrioLearn,cTrace0_WTStrioLearn,cTrace1_WTStrioLearn,...
    cTrace2_WTStrioLearn,cTrace3_WTStrioLearn] = getTraceLevels_QZ(twdb,...
    mouseIDs_WTStrioLearn);
% WT Matrix Learn
mouseIDs_WTMatrixLearn = unique(twdb_lookup(twdb,'mouseID','key','Health','WT',...
    'key','intendedStriosomality','Matrix','grade','learnedFirstTask',0,inf));
% mouseInfo_WTMatrixLearn = 'WT Matrix Learned';
[rTrace0_WTMatrixLearn,rTrace1_WTMatrixLearn,rTrace2_WTMatrixLearn,...
    rTrace3_WTMatrixLearn,cTrace0_WTMatrixLearn,cTrace1_WTMatrixLearn,...
    cTrace2_WTMatrixLearn,cTrace3_WTMatrixLearn] = getTraceLevels_QZ(twdb,...
    mouseIDs_WTMatrixLearn);
figure()
hold on
plotNoBar({cTrace3_WTStrioLearn,cTrace2_WTStrioLearn,cTrace1_WTStrioLearn,...
    cTrace0_WTStrioLearn,rTrace0_WTStrioLearn,rTrace1_WTStrioLearn,...
    rTrace2_WTStrioLearn,rTrace3_WTStrioLearn},...
    'Trace Sum',{'Cost Trace 3','Cost Trace 2','Cost Trace 1','Cost Trace 0',...
    'Reward Trace 0','Reward Trace 1','Reward Trace 2','Reward Trace 3'},...
    'WT Learn Mice Traces at Different Levels','b','b','b',1);
hold on
plotNoBar({cTrace3_WTMatrixLearn,cTrace2_WTMatrixLearn,cTrace1_WTMatrixLearn,...
    cTrace0_WTMatrixLearn,rTrace0_WTMatrixLearn,rTrace1_WTMatrixLearn,...
    rTrace2_WTMatrixLearn,rTrace3_WTMatrixLearn},...
    'Trace Sum',{'Cost Trace 3','Cost Trace 2','Cost Trace 1','Cost Trace 0',...
    'Reward Trace 0','Reward Trace 1','Reward Trace 2','Reward Trace 3'},...
    'WT Learn Mice Traces at Different Levels','r','r','r',1);
hold off
hold off
% %% Part V. Creating Tables
% WTLearnStrioTraceLevels = table(mouseIDs_WTStrioLearn',cTrace0_WTStrioLearn',cTrace1_WTStrioLearn',...
%     cTrace2_WTStrioLearn',cTrace3_WTStrioLearn',rTrace0_WTStrioLearn',...
%     rTrace1_WTStrioLearn',rTrace2_WTStrioLearn',rTrace3_WTStrioLearn',...
%     'VariableNames',{'WTStrioLearnIDs','Cost0Strio','Cost1Strio','Cost2Strio','Cost3Strio',...
%     'Reward0Strio','Reward1Strio','Reward2Strio','Reward3Strio'});
% WTLearnMatrixTraceLevels = table(mouseIDs_WTMatrixLearn',cTrace0_WTMatrixLearn',cTrace1_WTMatrixLearn',...
%     cTrace2_WTMatrixLearn',cTrace3_WTMatrixLearn',rTrace0_WTMatrixLearn',...
%     rTrace1_WTMatrixLearn',rTrace2_WTMatrixLearn',rTrace3_WTMatrixLearn',...
%     'VariableNames',{'WTMatrixLearnIDs','Cost0Matrix','Cost1Matrix','Cost2Matrix','Cost3Matrix',...
%     'Reward0Matrix','Reward1Matrix','Reward2Matrix','Reward3Matrix'});