function [CSaline_DZPS,CDZP_DZPS,CBase_DZPS,DSaline_DZPS,DDZP_DZPS,DBase_DZPS,...
    RTSaline_DZPS,RTDZP_DZPS,RTBase_DZPS,CTSaline_DZPS,CTDZP_DZPS,CTBase_DZPS,...
    CSaline_DZPM,CDZP_DZPM,CBase_DZPM,DSaline_DZPM,DDZP_DZPM,DBase_DZPM,...
    RTSaline_DZPM,RTDZP_DZPM,RTBase_DZPM,CTSaline_DZPM,CTDZP_DZPM,...
    CTBase_DZPM] = masterFunc_UPDATE2_QZ(twdb,dzpSIDs,dzpMIDs,conc,dzpData)
upToLearned = 0;
reversal = 0;
[~,~,dzpSRTones,dzpSCTones,dzpSN] = get_all_trials(twdb,dzpSIDs,upToLearned,reversal);
[~,~,dzpMRTones,dzpMCTones,dzpMN] = get_all_trials(twdb,dzpMIDs,upToLearned,reversal);
[~,~,CSaline_DZPS,CDZP_DZPS,CBase_DZPS,DSaline_DZPS,DDZP_DZPS,DBase_DZPS,...
    RTSaline_DZPS,RTDZP_DZPS,RTBase_DZPS,CTSaline_DZPS,CTDZP_DZPS,CTBase_DZPS] = calcAndPlotDZPUPDATE2_QZ(twdb,...
    dzpSIDs,dzpSRTones,dzpSCTones,dzpSN,['Strio ' num2str(conc) ' mg/kg'],dzpData);
[~,~,CSaline_DZPM,CDZP_DZPM,CBase_DZPM,DSaline_DZPM,DDZP_DZPM,DBase_DZPM,...
    RTSaline_DZPM,RTDZP_DZPM,RTBase_DZPM,CTSaline_DZPM,CTDZP_DZPM,CTBase_DZPM] = calcAndPlotDZPUPDATE2_QZ(twdb,...
    dzpMIDs,dzpMRTones,dzpMCTones,dzpMN,['Matrix ' num2str(conc) ' mg/kg'],dzpData);
end