% createDataTable3B.m
DATATABLE3B = table({learnWTM_IDs},{learnWTM_RZ},{learnWTM_RTS},...
    {learnWTM_CZ},{learnWTM_CTS},{periods},...
    'VariableNames',{'learnWTM_IDs','Reward_ZScore','RewardTraceSum',...
    'Cost_ZScore','CostTraceSum','periodsInOrder'});
% save('DATATABLE3B.mat','DATATABLE3B');