function devaluationCorrelation(twdb)

% Author: QZ
% 08/26/2019
% crossPlotsDZPDeval_UPDATE1.m
% deval part3, dzp part2
%% Part I. Deval Part 3 Update. No binning. Each Mouse is a data point.
devalData = devalData_UPDATE1(twdb);
% only learned WT
strioIDs = unique(twdb_lookup(table2struct(devalData),'mouseID',...
    'key','Health','WT','key','intendedStriosomality','Strio',...
    'grade','learnedFirstTask',0,inf));
upToLearned = 0;
reversal = 0;
[strioTrials,strioFTrials,strioRTones,strioCTones,strioN] = get_all_trials(twdb,...
    strioIDs,upToLearned,reversal);
[~,mouseIDsStrio,CWater_S,CSucrose_S,CBase_S,~,~,~,~,~,~,...
    RTWater_S,RTSucrose_S,RTBase_S,~,~,~,...
    ~,~,~] = calcAndPlotDevalUPDATE1_QZ(twdb,strioIDs,strioTrials,...
    strioFTrials,strioRTones,strioCTones,strioN,'Strio',devalData);
%% Part II. Data Table Creation
% DATATABLE = table(mouseIDsStrio',CWater_S',CSucrose_S',CBase_S',...
%     RTWater_S',RTSucrose_S',RTBase_S',(CBase_S-CWater_S)',(CBase_S-CSucrose_S)',...
%     (RTBase_S-RTWater_S)',(RTBase_S-RTSucrose_S)','VariableNames',{'mouseIDs',...
%     'CWater','CSucrose','CBase','RewardTraceWater','RewardTraceSucrose',...
%     'RewardTraceBase','CBaseminusCWater','CBaseminusCSucrose','RewardTraceBaseminusWater',...
%     'RewardTraceBaseminusSucrose'});